# 2. Data Frame
<p>A DataFrame represents a rectangular table of data and contains an ordered, named collection of <br>
columns, each of which can be a different value type (numeric, string, Boolean, etc.). <br>
The DataFrame has both a row and column index; <br>
it can be thought of as a dictionary of Series all sharing the same index</p>

In [1]:
import pandas as pd

In [2]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

<p>The resulting DataFrame will have its index assigned automatically, as with Series, <br>
and the columns are placed according to the order of the keys in data (which depends on their <br>
insertion order in the dictionary)<p>

In [3]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

the <b>head</b> method selects only the first five rows
the <b>tail</b> returns the last five rows

In [4]:
frame.head(), frame.tail()

(    state  year  pop
 0    Ohio  2000  1.5
 1    Ohio  2001  1.7
 2    Ohio  2002  3.6
 3  Nevada  2001  2.4
 4  Nevada  2002  2.9,
     state  year  pop
 1    Ohio  2001  1.7
 2    Ohio  2002  3.6
 3  Nevada  2001  2.4
 4  Nevada  2002  2.9
 5  Nevada  2003  3.2)

# Altering Columns
If you specify a sequence of columns, the DataFrame’s columns will be arranged in that order

In [5]:
pd.DataFrame(data, columns=["pop", "state", "year"])

   pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

## Passing a column not in dictionary
<p>Results in missing value (NaN)</p>

In [6]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [7]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

# Accessing Columns
<p>A column in a DataFrame can be retrieved as a Series either by <b>dictionary-like </b>notation
<br>
or by using the <b>dot attribute</b> notation</p>

In [8]:
frame2.state, frame2["state"]

(0      Ohio
 1      Ohio
 2      Ohio
 3    Nevada
 4    Nevada
 5    Nevada
 Name: state, dtype: str,
 0      Ohio
 1      Ohio
 2      Ohio
 3    Nevada
 4    Nevada
 5    Nevada
 Name: state, dtype: str)

## Loc and Iloc

In [9]:
frame2.loc[1], frame2.iloc[1]

(year     2001
 state    Ohio
 pop       1.7
 debt      NaN
 Name: 1, dtype: object,
 year     2001
 state    Ohio
 pop       1.7
 debt      NaN
 Name: 1, dtype: object)

In [10]:
frame.columns = ["Province", "Occur", "Num"]

frame

  Province  Occur  Num
0     Ohio   2000  1.5
1     Ohio   2001  1.7
2     Ohio   2002  3.6
3   Nevada   2001  2.4
4   Nevada   2002  2.9
5   Nevada   2003  3.2

In [11]:
import pandas as pd
import numpy as np

s = pd.Series(['a', 3, np.nan, 1, np.nan])

print(s.notnull().sum())

3

# Assigning values
## List or arrays
<p>When you are assigning lists or arrays to a column, the value’s length must match <br>
the length of the DataFrame. </p>
<p>If you assign a Series, its labels will be realigned exactly to the DataFrame’s index, <br>
insertingmissing values in any index values not present</p>

In [12]:
frame2["debt"] = [1.1, 3.1, 200, 500, 2, 1] # list or array is exact
frame2

   year   state  pop   debt
0  2000    Ohio  1.5    1.1
1  2001    Ohio  1.7    3.1
2  2002    Ohio  3.6  200.0
3  2001  Nevada  2.4  500.0
4  2002  Nevada  2.9    2.0
5  2003  Nevada  3.2    1.0

## Creating new column
<p>Assigning a column that doesn’t exist will create a new column.</p>

In [13]:
pay = pd.Series([200, 100], index=[5, 0])
frame2["Pay"] = pay
frame, frame2

(  Province  Occur  Num
 0     Ohio   2000  1.5
 1     Ohio   2001  1.7
 2     Ohio   2002  3.6
 3   Nevada   2001  2.4
 4   Nevada   2002  2.9
 5   Nevada   2003  3.2,
    year   state  pop   debt    Pay
 0  2000    Ohio  1.5    1.1  100.0
 1  2001    Ohio  1.7    3.1    NaN
 2  2002    Ohio  3.6  200.0    NaN
 3  2001  Nevada  2.4  500.0    NaN
 4  2002  Nevada  2.9    2.0    NaN
 5  2003  Nevada  3.2    1.0  200.0)

## Deleting Column

In [15]:
del frame2["Pay"]